package com.nitr.hellonitr.enums;

public enum DepartmentEnum {
    COMPUTERSCIENCE, ELECTRONICS, MECHANICAL, CIVIL, ELECTRICAL, CHEMICAL, PETROLEUM,
    AEROSPACE, BIOTECHNOLOGY, AGRICULTURE, ARCHITECTURE, MATHEMATICS, PHYSICS, CHEMISTRY, BIOLOGY
}
